server:
  port: 8080
name: 梦蛟龙
age: 35
content: "name:${name}, age:${age}"
student:
  name: livingbody
  age: 35
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/mdblog?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update #新增数据库连接必备的参数
